version: '3.9'

services:
  app:
    build:
      context: '.'
      dockerfile: './services/web-app/Dockerfile'

    container_name: 'app'

    ports:
      - '${ROBLOX_PLUS_APP_PORT:-}:3000'

    restart: 'always'

networks:
  default:
    name: 'roblox-plus'
    external: true
